tommerbob/polls/urls.py
from django.urls import path

from django.conf import settings
from django.conf.urls.static import static

from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = "polls"

urlpatterns = [
    path('', views.index, name='index'),
    path('home', views.index, name='index'),
    path('account', views.account, name='account'),
    path('<int:beverage_id>/', views.beverage_details, name='detail'),
    path('<int:beverage_id>/new_order/', views.new_order, name="new_order"),
    path('login', views.brugere, name="brugere"),
    path('<int:bruger_id>/login_request/', views.login_request, name="login_request"),
    path('logout', views.logout_view, name="logout"),
]

urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tommerbob/tømmerbob/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('polls.urls')),
    path('admin/', admin.site.urls),
]

tommerbob/polls/models.py
from django.db import models
from django.conf import settings
from django.db.models.base import Model
from django_mysql.models import ListCharField
from django.contrib.auth.models import User
import datetime
from django.core.files.storage import FileSystemStorage

from django.core.files import File
import os

# Create your models here.
class Bruger(models.Model):
    user_profile = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=20)
    account = models.IntegerField()
    profile_image = models.ImageField(upload_to='tommerbob/tømmerbob/polls/static/polls/images')


class Beverage(models.Model):
    title = models.CharField(max_length=100)
    desc = models.CharField(max_length=200)
    price = models.IntegerField(default=0)
    image = models.ImageField(upload_to='tommerbob/tømmerbob/polls/static/polls/images')
    stock = models.PositiveIntegerField(default=0)

    def __str__(self) -> str:
        return self.title

# Class to make an order for a user
class Order(models.Model):
    order = models.ForeignKey(Beverage, null=False, related_name='order', on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    price = models.IntegerField()
    date = models.DateField(default=datetime.datetime.today)
    user = models.ForeignKey(Bruger, null=True, on_delete=models.CASCADE)


    def placeOrder(self):
        self.save()

    def get_orders_by_customer(bruger_id):
        return Order.objects.filter(bruger=bruger_id).order_by('-date')

tommerbob/polls/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.template import loader
from django.http import Http404
from django.utils import timezone
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required

import logging
logging.basicConfig(level=logging.INFO) # Here

from .models import *

# Create your views here.
from django.http import HttpResponse

# @login_required(login_url="login")
def index(request):
    beverage_list = Beverage.objects.all()
    context = {
        'beverage_list': beverage_list
    }

    return render(request, 'polls/index.html', context)

@login_required(login_url="/login")
def account(request):
    user = Bruger.objects.get(id=request.user.id)
    orders = Order.objects.filter(user=user.id)
    user_orders = orders.order_by('date')
    credit = user.account
    total_orders = len(orders)

    context = {
        'order_list': user_orders,
        'credit': credit,
        'total_orders': total_orders
    }

    return render(request, 'polls/orders.html', context)

@login_required(login_url="/login")
def beverage_details(request, beverage_id):
    try:
        beverage = Beverage.objects.get(pk=beverage_id)
    except Beverage.DoesNotExist:
        raise Http404("Beverage does not exist")
    return render(request, 'polls/detail.html', {'beverage': beverage})

def login_request(request, bruger_id):
    if request.method == "POST":
        logging.info("Got post request")
        username = Bruger.objects.get(pk=bruger_id).user_profile
        password = "password"
        user = authenticate(username=username, password=password)
        logging.info(user)
        if user is not None:
            login(request, user)
            logging.info(request, f"You are now logged in as {username}.")
            return redirect("/")
        else:
            logging.error(request,"Invalid username or password.")
    else:
        logging.error(request,"Invalid username or password.")

    return redirect("/")

def brugere(request):
    bruger_list = Bruger.objects.all()
    context = {
        'bruger_list': bruger_list
    }
    return render(request=request, template_name="polls/login.html", context=context)


def logout_view(request):
    logout(request)
    return redirect('/')

@login_required(login_url="/login")
def new_order(request, beverage_id):
    quantity = request.POST['amount']
    print(f"REQUEST USER ID: {request.user.id}")
    user = Bruger.objects.get(id=request.user.id)
    print(f"BRUGER OBJECT: {user.name}")
    ordered_bev = Beverage.objects.get(id=beverage_id)
    order = Order.objects.create(user=user, order = ordered_bev, 
            quantity=quantity, price=int(quantity)*ordered_bev.price)

    user.account = user.account - order.price
    user.save()

    order.save()

    return redirect("/")

tommerbob/polls/templates/polls/detail.html
{% extends "polls/header.html" %}

{% block content %}    

<div class="centering">
<h1>{{ beverage.title }}</h1>
<img src="{{ beverage.image.url }}" alt="{{ beverage.image.url }}">
<form action="{% url 'polls:new_order' beverage.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        <h5>Amount</h5>
        <div class="minus-btn btn btn-primary">-</div>
        <input type="text" name="amount" id="amount" value="1">
        <div class="plus-btn btn btn-primary">+</div>
    </fieldset>
    <input class="btn btn-primary" type="submit" value="submit">
    </form>
</div>

<style>
.centering {
    text-align: center;
}

input {
    text-align: center;
}

.plus-btn {
    padding-left: 25px;
    padding-right: 25px;
}

.minus-btn {
    padding-left: 25px;
    padding-right: 25px;
}

</style>

<script type="text/javascript">

document.querySelector(".plus-btn").addEventListener("click", function() {

    var amount

    amount = document.getElementById("amount").value;
    amount ++;
    document.getElementById("amount").value = amount


})

document.querySelector(".minus-btn").addEventListener("click", function() {

    var amount

    
    amount = document.getElementById("amount").value;
    if (amount > 0) {
    amount --;
    document.getElementById("amount").value = amount
    }

})

</script>

{% endblock %}

tommerbob/polls/templates/polls/header.html
<!DOCTYPE html>
<html>
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    {% load static %}

    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

    <title>TømmerBob</title>
  </head>
 <body>
  {% if user.is_authenticated %}

    <center><h4>Logget ind som {{ user.get_username }} <br></br> <a class="btn btn-primary" type="submit", href="/">Home</a> - <a class="btn btn-primary" type="submit", href="/account">Account</a> - <a class="btn btn-primary" type="submit", href="/logout">Logout</a></h4></center>

  {% else %}

    <center><h4>Ikke logget ind <br></br> <a class="btn btn-primary" type="submit", href="login">Login</a> - <a class="btn btn-primary" type="submit", href="/">Home</a></h4></center>

  {% endif %}

    {% block content %}

    {% endblock %} 
      
  </body>
</html>

tommerbob/polls/templates/polls/index.html
{% extends "polls/header.html" %}

{% block content %}    


{% if beverage_list %}
<div class="grid-container">
    {% for beverage in beverage_list %}
    <div class="card" style="width: 20rem;">
      <img class="card-img-top" src="{{ beverage.image.url }}" alt="{{ beverage.image.url }}">
      <div class="card-body text-center">
        <h5 class="card-title">{{ beverage.title }}</h5>
        <p class="card-text">{{ beverage.desc }}</p>
        <p class="card-text">Price - {{ beverage.price }}</p>
        <a href="/{{ beverage.id }}/" class="btn btn-primary">Buy Now</a>
      </div>
    </div>
    {% endfor %}
</div>
{% else %}
    <p>No beverages registered.</p>
{% endif %}

<style>

img {
  width: auto;
}

.card {
  margin: 1rem;
  padding: 1rem;
}

.grid-container {
  align-items: center;
  display: inline-grid;
  grid-template-columns: auto auto auto;
  padding: 5px;
}

</style>

{% endblock %}

tommerbob/polls/templates/polls/login.html
{% extends "polls/header.html" %}

{% block content %}    

{% if bruger_list %}
<div class="grid-container">
    {% for bruger in bruger_list %}
    <div class="card centered" style="width: 20rem;">
      <!-- ADD IMAGE PROPERTY TO BRUGER OBJECT -->
      <form action="{% url 'polls:login_request' bruger.id %}" method="post">
        {% csrf_token %}
        <fieldset>
            {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
            <img class="card-img-top" src="{{ bruger.profile_image.url }}" alt="{{ bruger.profile_image.url }}">
            <h5>{{ bruger.name }}</h5>
        </fieldset>
        <input class="btn btn-primary" type="submit" value="Login">
        </form>
      </div>
    </div>
    {% endfor %}
</div>
{% else %}
    <p>No users registered.</p>
{% endif %}

<style>

  img {
    width: auto;
  }
  
  .card {
    margin: 2rem;
    padding: 1rem;
  }
  
  .grid-container {
    align-items: center;
    display: inline-grid;
    grid-template-columns: auto auto auto;
    padding: 5px;
  }

  .centered {
    text-align: center;
  }
  
  </style>

{% endblock %}

tommerbob/polls/templates/polls/orders.html
{% extends "polls/header.html" %}

{% block content %}

{% if order_list %}

<h5 class="card-title">Total Orders: {{ total_orders }}</h5>
<h5 class="card-title">Current Account Credit: {{ credit }} kr</h5>

<div>
<body style="font-family:'Helvetica Neue', Arial; font-size: 16px;">
	<h3>{{ chartTitle|safe }}</h3>
	<div id="chart-1">{{ output|safe }}</div>
	<div id="chart-2">{{ output_2|safe }}</div>
	<br/>
	<a href="/">Back</a>
</div>

<div>
    <ul>
        {% for order_ in order_list %}
        <div class="card" style="width: 18rem;">
          <div class="card-body">
            <h5 class="card-title">{{ order_.order.title }}</h5>
            <p class="card-text">Amount: {{ order_.quantity }}</p>
            <p class="card-text">Total Price: {{ order_.price }}</p>
            <p class="card-text">Date Ordered: {{ order_.date }}</p>
          </div>
        </div>
        {% endfor %}
    </ul>
</div>
{% else %}
    <p>No orders registered.</p>
{% endif %}

{% endblock %}